export default {
  createVoting: "Create-Voting",
  addVoting: "Add-Voting",
  updateVoting: "Update-Voting",
  addMeeting: "Add-Meeting",
  refreshScheduleList: "refresh-meeting-list-screen",
  refreshMeetingDetail: "refresh-meeting-detail-screen",
  refreshTaskDetail: "refresh-task-detail-screen",
  refreshTaskStatus: "refresh-task-status-screen",
  refreshFAQList: "refresh-faq-list-screen",
  reactEmoji: "react-emoji",
  refreshHomePage: "refresh-homepage-screen",
  addMeetingToChat: "add-meeting-to-chat",
  addTaskToChat: "add-task-to-chat",
  refreshWorkspace: "refresh-workspace-screen",
};
