name: Deploy to Google (Version 1)

on:
  push:
    branches:
      - develop
    paths:
      - src
      - .github/workflows/deloy-to-google.yml

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.yarnpkg.com"

      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          # Adding node version as cache key
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

      - name: Install dependencies
        run: yarn install

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: Build and sign APK
        run: |
          cp ./.env.prod ./.env
          cd android
          ./gradlew bundleRelease

      - name: Upload APK to Google Play
        run: |
          fastlane supply --track production --json_key ${{ secrets.GOOGLE_PLAY_JSON_KEY }} --package_name com.mentorus --apk app-release.aab --skip_upload_metadata --skip_upload_images --skip_upload_screenshots
